# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Karpx < Formula
  desc "⚡ Karpenter for EKS — managed from your terminal"
  homepage "https://github.com/kemilad/karpx"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.7/karpx_darwin_amd64.tar.gz"
      sha256 "fb6a8c8eb790d66cdc4a0517b2c8321f1545bcf58d8f15158f5c28fdd7733424"

      define_method(:install) do
        bin.install "karpx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.7/karpx_darwin_arm64.tar.gz"
      sha256 "cd8ddfa61413f000aa2f8a627ee6314b4f6ae1bc1117bd5a0230bdebe2c99ab8"

      define_method(:install) do
        bin.install "karpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.7/karpx_linux_amd64.tar.gz"
      sha256 "fadabd7db2175fbb31e1dea30d3f443452b000a43755bb9c12101ceffb3e7914"
      define_method(:install) do
        bin.install "karpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.7/karpx_linux_arm64.tar.gz"
      sha256 "a6888f70449b8ab5a3693dd1962002b3d1d2213ec940cb1a7a97cbc074c7fc7a"
      define_method(:install) do
        bin.install "karpx"
      end
    end
  end

  def caveats
    <<~EOS
      Run `karpx` to open the interactive TUI.

      Requirements:
        - kubectl configured with your EKS cluster contexts
        - AWS credentials (env vars, ~/.aws/credentials, or IAM role)

      Quick start:
        karpx                          open TUI (current context)
        karpx -c my-cluster            target a specific cluster
        karpx -c my-cluster -r us-east-1
    EOS
  end

  test do
    assert_match "karpx", shell_output("#{bin}/karpx version")
  end
end
