# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Karpx < Formula
  desc "⚡ The Kubernetes essentials toolkit"
  homepage "https://github.com/kemilad/karpx"
  version "0.1.42"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.42/karpx_darwin_amd64.tar.gz"
      sha256 "916839ca4f4e0ce85923f6149e6fb72a5bf8a29a6b62e360164f391f68f8fc2c"

      define_method(:install) do
        bin.install "karpx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.42/karpx_darwin_arm64.tar.gz"
      sha256 "482b00a02400c33b9f0affc20b051dd9f9bfa7d59af351a1db3c67a69d601d9c"

      define_method(:install) do
        bin.install "karpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.42/karpx_linux_amd64.tar.gz"
      sha256 "92c165d32ab96b21635b35a51c4df6fd078e0aa57bf5bd75589bdd26fe936e54"
      define_method(:install) do
        bin.install "karpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.42/karpx_linux_arm64.tar.gz"
      sha256 "304efb8c2207d0091ef848a48527a15b57230b3bb6c17debeaf85a36d2dbafbb"
      define_method(:install) do
        bin.install "karpx"
      end
    end
  end

  def caveats
    <<~EOS
      Run `karpx` to open the interactive TUI.

      Requirements:
        - kubectl configured with your EKS cluster contexts
        - AWS credentials (env vars, ~/.aws/credentials, or IAM role)

      Quick start:
        karpx                          open TUI (current context)
        karpx -c my-cluster            target a specific cluster
        karpx -c my-cluster -r us-east-1
    EOS
  end

  test do
    assert_match "karpx", shell_output("#{bin}/karpx version")
  end
end
