# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Karpx < Formula
  desc "⚡ Karpenter for EKS — managed from your terminal"
  homepage "https://github.com/kemilad/karpx"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.5/karpx_darwin_amd64.tar.gz"
      sha256 "ca679feb948d77cbc31760238db5b7478229716e6e445c7c0bbd97c52a5095a9"

      define_method(:install) do
        bin.install "karpx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.5/karpx_darwin_arm64.tar.gz"
      sha256 "7e9ac055dd8adec6bb3dee94eca629ba8b161d46919bb17d5291e40d41f4d220"

      define_method(:install) do
        bin.install "karpx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.5/karpx_linux_amd64.tar.gz"
      sha256 "981519d9e57e51631ec8a3e3558f623b85c8af612c0cab2fd0156047680556ba"
      define_method(:install) do
        bin.install "karpx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemilad/karpx/releases/download/v0.1.5/karpx_linux_arm64.tar.gz"
      sha256 "0f13437da97511abfc5ac9fb20957f7549c51c1ac713bbb012641f63552cb88a"
      define_method(:install) do
        bin.install "karpx"
      end
    end
  end

  def caveats
    <<~EOS
      Run `karpx` to open the interactive TUI.

      Requirements:
        - kubectl configured with your EKS cluster contexts
        - AWS credentials (env vars, ~/.aws/credentials, or IAM role)

      Quick start:
        karpx                          open TUI (current context)
        karpx -c my-cluster            target a specific cluster
        karpx -c my-cluster -r us-east-1
    EOS
  end

  test do
    assert_match "karpx", shell_output("#{bin}/karpx version")
  end
end
